### ISSUE TITLE
Can't find `final` branch

### ISSUE THREAD

**Issue by avinassh** [DjangoPatternsBook/superbook#7]
I want to see the final site, but I see no `final` branch exists. 

and also, in book, it says `cd` into `final` directory, where no such directory also exists.

**Comment by andy-io** [comment]
yes, i could also not find the final branch or final directory. Could you please help us Arun ?

**Comment by arocks** [comment]
Hi @avinassh and @andy-io ,

The final branch is now available at: https://github.com/DjangoPatternsBook/superbook/tree/final

It is not fully done and was actually intended to be an exercise for the reader :smile:

**Comment by avinassh** [comment]
I am not sure if it was intended as an exercise for the user, since it is mentioned at couple of places for the user to check. Anyways, you replied way too late for this issue filed and I don't remember anything much (I put down the book long back).
